grafana:
  url: "http://127.0.0.1:3000"
  contactPointName: Opfab alerting service
operatorfabric:
  servicesUrls:
    authToken: "http://127.0.0.1:2002/auth/token"
    cardsPublication: "http://127.0.0.1:2102"
    users: "http://127.0.0.1:2103"
  internalAccount:
    login: opfab
    password: test
  alerting:
    cardTemplate:
      publisher: opfab
      processVersion: '1'
      process: alertingProcess
    panelRangeOffsetMs: 60000
    port: 2109
    mapping:
      configFilePath: "mapping/config.json"
      defaultMappingData:
        cardTitle: Grafana alerting
        firingSeverity: ALARM
        resolvedSeverity: COMPLIANT
